sudo: required
services:
  - docker

before_install:
  - docker build -t telstratxynidakis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true telstratxynidakis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-008658973142"
  bucket_path: "docker"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secure_access_key:
  secure: "$AWS_SECRET_KEY"

